language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # LOCAL_SECRET
    - secure: pc9wo/CrVxOG+ob2NHSknix33dlFIG8sWS3x33wPXX9wlgxHBqaXj5JbqSiak8coep+NOonfxE9vBR1CkToNV+tz6oaL5IijTQ/pFtce3aaEIaimmutbBUPVMiIvqE20wqaBtcLh/4eq5g9j/kFb+jwWmzWyRya9kEvFa/GD1/6dnAiZr6Q7W6L4/YUBS4e/HgS1UP8HHjo4CT+w9TG21+0mjk42aZKyAki0L5a3uVX7eHw3pkijRgb87aBoQF8PuTX/U4Yp+XMlXoWigDYxcvp29yobjvBExuW4G1hbSccPEZj5nzctQlWmqhv21eXdvahZuv4w/IGN5dVpInUMudvy9ZmMwYUXSuQnS3XWjJbB/QsVTztBcKVJprjSYy4ag2sLKxxzNsdX9uI/fOqI29MtoZGMQZ9WS+OeY1AB2xEVrc4xeA3Y3zqX8ALGIEvOfUAvvxBaHWt+gMNuEbrDVbfvee0rqf3atF3i/rhUBvnF1LymqtQaNMqT2rPNmgnHSYoKBedM3t9OjH47quxcI/sCqkbWuQwz0tPMwABL5WsWfTDKfCzo69MEU4u/HsiqvzSA7Gs+/R6gvQTdpoJSAaGQvzubqHY/KwsOKV/6lf7xG2cHmEE23BfT9db0t236ANKD3Nl3SpWiyK/H7CTwqWEvhPlbeXW2QEEQcAeK+z4=
    # LOCAL_TOKEN
    - secure: sHNB/tPTwFbCJOmZkbt1owml3TLG1grEnTJ9NBHW70F044FXTbYy5gUlkTYnk4hLfdmy2esadVmPfS4qEjRMX+6SSpCuFGwhvA9b0VYPFIHsqGQJTxSxVoBaLksUbomQQ8aga9RNQCkkCgZMGiMdrJ6MrAz3LFlMezex6paBmFyqRgWSwdcJ/8RbCciLLW3IHww5XzH8+zAYHNLwUClXJ71/l+0XtqaiSr731QY0IfjzpNEeIrTIwPfMJfl1gPq8j1zNxPJ8bS/Sl8VPXGuc6lHRHQ53dMVcRLbxkJ2XSQQ7N/s71poNHzsDK2jTQZ8UB5pgkCZKcaDc8FVA5jsmkarvzD7gBGSuswPo3aUn9z2NBoU13CUmFcZaAAFCCw97y+PUuS8RJUXD7asRoNlCPrYc8WghGEoK0Jhhd5eHI1W88Vv0PvryDaoJ9eBfKrdkUR5wQ9XXSEndw4NhVXrjXymfOJfI2Ws2ZS38+R5M0YJUISodJbOCfgLwfgmo3fo9Lf5lXOxEOS5tUwne/xro/iAY2rx9pW5Y7K6cMdjGHFdID24dxmbIZop2jnGkqrcgPtwUZ/8pKYajc3UF0hf3/zAPTk0ocSZ9kZs0SmfQlbmTJmskHxZVT42IIUA336VyEhMUj9DQMVH3kcu6h6gz0taV01nXXLhJJueWu28qUMY=
